[project]
name = "max-resend"
version = "1.0.0"
description = "simple script for resend messages from max to telegram chat"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "pydantic>=2.12.2",
    "websockets>=15.0.1",
]
